### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#10]
1. Разные цвета у иконок.
![different colors](https://user-images.githubusercontent.com/51824674/91168595-b539dc00-e6f7-11ea-80c1-57383ba67613.png)

2. Отзывы сделать ссылкой, для рейтинга добавить хотя бы cursor pointer.
![links pointer](https://user-images.githubusercontent.com/51824674/91168725-eadec500-e6f7-11ea-8428-bd8b23046bda.png)

3. Инпутам добавить соответствующий type.
![types](https://user-images.githubusercontent.com/51824674/91168760-f92ce100-e6f7-11ea-818d-a0082e9acb30.png)

4. Зона, для которой установлен cursor pointer отличается от кликабельной зоны.
![to big pointer](https://user-images.githubusercontent.com/51824674/91168866-28dbe900-e6f8-11ea-90d4-4878a3642d91.gif)

5. Календарь работает странно, неудобно выбирать дату отъезда, потому что при этом не видно даты прибытия, очистка поля удаляет маску, и даты до текущей лучше сделать неактивными.
![uncomf](https://user-images.githubusercontent.com/51824674/91169192-ba4b5b00-e6f8-11ea-8deb-2e9c8b3ae0f1.gif)

**Comment by GrigorenkoSergey** [comment]
Исправил все.

**Comment by iatsdotfatr** [comment]
1. Нельзя выбрать даты следующего месяца, кнопки применить бесполезная
![apply button](https://user-images.githubusercontent.com/51824674/91579906-1ff44d00-e96e-11ea-9a6c-743b9b50fc8c.gif)
![next month](https://user-images.githubusercontent.com/51824674/91579914-2256a700-e96e-11ea-9714-c5c133e5ec24.gif)

2. У инпутов с возможностью ввода данных cursor pointer, должен быть text.

3. При добавлении текста чекбокс ломается
![text overflow](https://user-images.githubusercontent.com/51824674/91580388-d6583200-e96e-11ea-9bad-bb9061e34516.png)

4. Нет изменения hover состояния при наведении на ссылку. При нажатии на ссылку-дропдаун происходит переход.
![no hover](https://user-images.githubusercontent.com/51824674/91580507-099ac100-e96f-11ea-8f64-76f4b9099d00.png)
![hover](https://user-images.githubusercontent.com/51824674/91580527-115a6580-e96f-11ea-9a11-c191703aa5c0.png)

5. Нет отступа у логотипа на случай длинного текста.
![offset](https://user-images.githubusercontent.com/51824674/91580668-3d75e680-e96f-11ea-867b-0255a17eceb2.png)

6. Здесь тоже должен открываться календарь.
![Screenshot from 2020-08-28 20-23-34](https://user-images.githubusercontent.com/51824674/91580863-8463dc00-e96f-11ea-8d9d-3d4c7fd8f925.png)

7. Тоже сделать ссылками, посмотреть в best practices какие атрибуты добавлять к ссылкам на сторонние ресурсы
![links](https://user-images.githubusercontent.com/51824674/91581063-c7be4a80-e96f-11ea-8314-4af84e184fdd.png)

8. 
![Screenshot from 2020-08-28 20-32-20](https://user-images.githubusercontent.com/51824674/91581079-d0168580-e96f-11ea-8821-63a993490ebe.png)
![Screenshot from 2020-08-28 20-31-50](https://user-images.githubusercontent.com/51824674/91581097-d573d000-e96f-11ea-9e98-4cade300a104.png)

**Comment by GrigorenkoSergey** [comment]
Исправил.

**Comment by iatsdotfatr** [comment]
Hover эффект должен быть таким же, как и у ссылок в футере, у ссылок в хедере также должен быть ховер эффект, по-прежнему происходит переход при нажатии на дропдаун.
![hover](https://user-images.githubusercontent.com/51824674/91972561-b644bc00-ed3c-11ea-982c-f2bc4dc2cee7.gif)

**Comment by GrigorenkoSergey** [comment]
Исправил.

**Comment by iatsdotfatr** [comment]
К этому тоже относится.
![hover](https://user-images.githubusercontent.com/51824674/92202406-bfe73480-eea0-11ea-9d21-e83bc125eb8f.gif)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Слишком длинная ссылка
![big link](https://user-images.githubusercontent.com/51824674/92612625-db58a200-f2db-11ea-98bd-7a1ec0615a5c.gif)

2. Позиционируй меню абсолютно
![poa](https://user-images.githubusercontent.com/51824674/92612744-fa573400-f2db-11ea-8b24-013efdef7c9c.gif)

**Comment by GrigorenkoSergey** [comment]
Починил.
