### ISSUE TITLE
Pixel Perfect

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#11]
1. Cards на 1440px.
![noperf](https://user-images.githubusercontent.com/51824674/91972794-01f76580-ed3d-11ea-8f35-d8f3ae0b4182.png)

2. Headers and Footers.
![Screenshot from 2020-09-02 16-44-59](https://user-images.githubusercontent.com/51824674/91972837-10de1800-ed3d-11ea-8037-444e8837c990.png)

3. Signin.
![signin](https://user-images.githubusercontent.com/51824674/91972887-25221500-ed3d-11ea-8d7b-89685df4045c.png)

4. Filter.
![filter](https://user-images.githubusercontent.com/51824674/91972929-366b2180-ed3d-11ea-8cf5-33037bc6c0d1.png)

5. Registration.
![registration](https://user-images.githubusercontent.com/51824674/91972978-48e55b00-ed3d-11ea-9bd7-9c5fa25df55f.png)

6. Room details.
![room](https://user-images.githubusercontent.com/51824674/91973020-5864a400-ed3d-11ea-9daf-ceb9978973fc.png)

В некоторых случаях несовпадения могут быть из-за того, что на фигме обновлялись макеты, скачай текущие.

**Comment by GrigorenkoSergey** [comment]
Исправил все. Скачанные свежие макеты в папке src/template-images.

**Comment by iatsdotfatr** [comment]
1. Form elements
![form els](https://user-images.githubusercontent.com/51824674/93079394-e03b9e00-f6ad-11ea-8b75-4d61502343f1.png)

2. Headers&Footers
![h F](https://user-images.githubusercontent.com/51824674/93079423-ea5d9c80-f6ad-11ea-8165-97fac781a9f5.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
Жирная граница в search.
![ft border](https://user-images.githubusercontent.com/51824674/93187799-03278a00-f762-11ea-95c6-95ebd9d9298a.png)

**Comment by GrigorenkoSergey** [comment]
Исправил.
