### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#12]
1. На разрешениях экрана больше 1440px все съезжает, для содержимого можно сделать фиксированный контейнер и выравнивать его по центру экрана, картинки растягивать по ширине на весь экран.
![hirez](https://user-images.githubusercontent.com/51824674/92204470-62091b80-eea5-11ea-92ba-a36a1837ad3a.png)

2. Ссылки и кнопки убирать в выпадающее меню на 768px.
![ins menu](https://user-images.githubusercontent.com/51824674/92204116-97613980-eea4-11ea-9984-24b5f42b5e9a.png)

3. В UI-kit есть вариант футера для разрешения 768px.
![to close](https://user-images.githubusercontent.com/51824674/92204335-0c347380-eea5-11ea-9457-e06dcdd0851a.png)

4. Всегда должны быть отступы между карточкой и краями окна просмотра, на мобильных разрешениях картинку можно обрезать до уровня чуть больше карточки или скрыть вообще.
![top pic](https://user-images.githubusercontent.com/51824674/92204785-10ad5c00-eea6-11ea-93f1-a5786d0dd654.png)

5. Здесь отступы есть, но инпут выпадает из карточки.
![input scroll](https://user-images.githubusercontent.com/51824674/92205030-a34dfb00-eea6-11ea-9425-a718d89a7e4e.png)

6. Календарь на 320px не вмещается по ширине.
![datepicker scroll](https://user-images.githubusercontent.com/51824674/92204875-48b49f00-eea6-11ea-9251-cd8af3e63d7c.png)
 
7. Адаптация часто происходит не вовремя, появляется горизонтальная прокрутка, проверить все страницы.
![room scroll2](https://user-images.githubusercontent.com/51824674/92205113-cf697c00-eea6-11ea-886c-2a71de5f07a0.png)

![room scroll](https://user-images.githubusercontent.com/51824674/92205115-d2646c80-eea6-11ea-862c-13e221afc896.png)

![room scroll3](https://user-images.githubusercontent.com/51824674/92205082-bfea3300-eea6-11ea-8351-96b691a9f6d3.png)

![filter scroll](https://user-images.githubusercontent.com/51824674/92205136-df815b80-eea6-11ea-8202-d576fddc05c0.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Меню пусть сразу открывается в итоговом варианте, без последующей адаптации строк/столбцов.
![bd](https://user-images.githubusercontent.com/51824674/92613787-27f0ad00-f2dd-11ea-84d8-fce14b75afee.png)

2. Слишком близко.
![close](https://user-images.githubusercontent.com/51824674/92613874-3f2f9a80-f2dd-11ea-94bb-37eb5e0dfc83.png)

3. На лэндинге есть момент, где отступов от окна просмотра нет вообще, потом появляется только с одной стороны, с карточками на других страницах тоже проблемы с отступами.
![filter](https://user-images.githubusercontent.com/51824674/92614150-89188080-f2dd-11ea-82f5-a05e0a07af72.png)
![reg](https://user-images.githubusercontent.com/51824674/92614157-89b11700-f2dd-11ea-9648-ad51a9f8d99d.png)
![tclose](https://user-images.githubusercontent.com/51824674/92614158-8a49ad80-f2dd-11ea-9e86-c004426dd20b.png)
![too close](https://user-images.githubusercontent.com/51824674/92614160-8a49ad80-f2dd-11ea-8191-b49ec447f6c2.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Нет отступа, как и у карточек  ранее.
![no offset](https://user-images.githubusercontent.com/51824674/92739215-77e37880-f39e-11ea-928f-1cdf8450da17.png)

2. Некорректное отображение на больших разрешениях, сделай так, чтобы футер на всех страницах был прижат к нижней части окна просмотра (на интервью в разделе css будет этот вопрос).
![correct fullscreen](https://user-images.githubusercontent.com/51824674/92740122-4f0fb300-f39f-11ea-9317-d095431ec283.png)

**Comment by GrigorenkoSergey** [comment]
Готово.
