### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by AkhmadBabaev** [GrigorenkoSergey/FSDEducation-second-task#15]
https://github.com/GrigorenkoSergey/FSDEducation-second-task/blob/52975534577ee98632d0f3049319e1a3910e88f0/webpack.config.js#L3

https://github.com/GrigorenkoSergey/FSDEducation-second-task/blob/52975534577ee98632d0f3049319e1a3910e88f0/src/assets/blocks/dropdown/dropdown-item.js#L7

Старайся удалять не используемые переменные )

**Comment by AkhmadBabaev** [comment]
Файлы экспортирующие класс принято именовать так же как и класс(нотация PascalCase).

**Comment by AkhmadBabaev** [comment]
Приватные свойства и методы следуют именовать с нижнего подчеркивания, тайпскрипта это не касается.

**Comment by AkhmadBabaev** [comment]
Все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-.

**Comment by AkhmadBabaev** [comment]
https://github.com/GrigorenkoSergey/FSDEducation-second-task/blob/e59fc48df0c3b661341abe00b44e48214a1876e7/src/assets/blocks/cards/cards.js#L1-L8

Предполагаю что у тебя есть собственная сортировка импортов, мы сортируем способом описанным в лучших практиках [тут](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.17).

**Comment by AkhmadBabaev** [comment]
https://github.com/GrigorenkoSergey/FSDEducation-second-task/blob/c6ea82fb587e3182d0116a40a0d67d76473a2110/src/assets/blocks/dropdown-guests/DropdownGuests.js#L11-L15

Можно использовать пакет autobind-decorator для привязки методов к классу вместо создания для этого отдельных методов ) А так же обрати внимание на вызов super._bindHandlers();, это довольно необычная конструкция ИМХО, возможно она говорит об ошибках конструирования компонентов, пересмотри этот участок кода, может она вовсе не нужна или может получится переиграть эту логику.

**Comment by AkhmadBabaev** [comment]
https://github.com/GrigorenkoSergey/FSDEducation-second-task/blob/c6ea82fb587e3182d0116a40a0d67d76473a2110/src/assets/blocks/dropdown/DropdownOrigin.js#L49-L52

Методы в классах сортируем в следующем порядке, сперва публичные, потом защищенные, потом приватные, так что update должен быть выше.

**Comment by AkhmadBabaev** [comment]
https://github.com/GrigorenkoSergey/FSDEducation-second-task/blob/c6ea82fb587e3182d0116a40a0d67d76473a2110/src/assets/blocks/datepicker/Datepicker.js#L31-L44

Пересмотри код на правило о времени жизни переменных [ссылка на best-practices](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.7). 

Пример
```js
    buttonReset.classList.add('datepicker--button-reset');
    buttonReset.innerHTML= 'Очистить';
    buttonReset.addEventListener('click', this._handleButtonResetClick.bind(this));
```

**Comment by GrigorenkoSergey** [comment]
Хм... сообщение в коммите fix #15 закрывает issue. О как..
