### ISSUE TITLE
Разное

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#3]
1. После npm run dev лучше открывать меню с навигацией по страницам.

2. 
![fonts](https://user-images.githubusercontent.com/51824674/85201375-9ea28d80-b320-11ea-93b0-c9a9158cfcad.png)

3. Убрать лишние комментарии по всему проекту
![no comments](https://user-images.githubusercontent.com/51824674/85201403-c98ce180-b320-11ea-9ffb-344b67a4f14f.png)

4. Br здесь не надо использовать
![no br](https://user-images.githubusercontent.com/51824674/85201414-dd384800-b320-11ea-9e51-5f6bfcc3181d.png)

5. Favicons убрать в src, sass-cache и vscode в gitignore
![Screenshot from 2020-06-20 17-47-30](https://user-images.githubusercontent.com/51824674/85201438-225c7a00-b321-11ea-8bda-edbce3c3c5b7.png)

**Comment by GrigorenkoSergey** [comment]
1) Не осилил, т.к. не особо представляю, что нужно сделать. 
2) Поменял.
3) Комментарии убраны, оставлены только поясняющие и примеры использования.
4) Убрал <br /> по всем страницам кроме form_elements и search_room, т.к. не понял логики переноса по словам в данных rich-checkbox.

**Comment by iatsdotfatr** [comment]
1. Сейчас при запуске выводится страница form-elements. Сделай страницу со ссылками на все страницы проекта и выводи ее при запуске. То есть примерно то же самое, что в readme:
![Screenshot from 2020-06-23 13-11-36](https://user-images.githubusercontent.com/51824674/85372141-3982ae00-b553-11ea-82a6-e65b1e0f5736.png)
2. Да, шрифты переименовать, гитхаб может игнорировать изменения регистра, проверь на самом сайте после переименования.

**Comment by GrigorenkoSergey** [comment]
О, круто! ))) Оперативненько ))
1. Пункт. Додумался только до такого решения в лоб. Годится, или нужно что-то поизящнее? Остальные возможные варианты у меня почему-то все связаны с Node.js.

**Comment by iatsdotfatr** [comment]
Норм

**Comment by GrigorenkoSergey** [comment]
2 Пункт. Шрифты переименованы.

**Comment by iatsdotfatr** [comment]
Теперь можно в readme давать одну ссылку на все страницы

**Comment by GrigorenkoSergey** [comment]
Сделал.

**Comment by iatsdotfatr** [comment]
1. В данном случае делай вложение модификатора в элемент, т.е. &_модификатор
![inside](https://user-images.githubusercontent.com/51824674/88416582-4587b700-ce02-11ea-9599-e18ac965bf60.png)

2. Здесь тоже используй lowercase-hyphenated, как и в scss-переменных 
![lower-case](https://user-images.githubusercontent.com/51824674/88416655-66e8a300-ce02-11ea-8727-5bd49e355b61.png)

3. Автопрефиксер же установлен, и правило placeholder есть префикса
![prefixes](https://user-images.githubusercontent.com/51824674/88416831-b3cc7980-ce02-11ea-88dc-3c7d6df253e9.png)

4. Смесь pug с html
![pug vs html](https://user-images.githubusercontent.com/51824674/88416859-c3e45900-ce02-11ea-8024-ca491340849a.png)

**Comment by GrigorenkoSergey** [comment]
Вложил, переименовал, убрал, убрал.

**Comment by iatsdotfatr** [comment]
Поставь импорты над переменными
![imports over vars](https://user-images.githubusercontent.com/51824674/91167784-5aec4b80-e6f6-11ea-820b-c0ef2e3ffbe8.png)

**Comment by GrigorenkoSergey** [comment]
Исправил.

**Comment by iatsdotfatr** [comment]
1. Ключ-значение
![kv](https://user-images.githubusercontent.com/51824674/93079828-90110b80-f6ae-11ea-86bf-ae79dbad9ae1.png)

2. Это ридми удали или убери в гитигнор, если оно для тебя важно.
![Screenshot from 2020-09-14 17-14-05](https://user-images.githubusercontent.com/51824674/93079923-b9319c00-f6ae-11ea-8ce1-7e660d4fff37.png)

3. Удали все комментарии, кроме тех, что связаны с линтером.

**Comment by GrigorenkoSergey** [comment]
Готово.
