### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#4]
Скрипты переписать на ES6-классы.
![es6](https://user-images.githubusercontent.com/51824674/85201466-56d03600-b321-11ea-814b-652eedfbac83.png)

**Comment by GrigorenkoSergey** [comment]
Начал. Пока переделал dropdown.

**Comment by GrigorenkoSergey** [comment]
Переписал все, кроме range-slider (т.к. это 4-е задание). Так же не стал создавать классы на checkbox  и toggler, т.к. в них я только убираю выделение текста по умолчанию. Создавать класс для этого, по-моему, избыточно.

**Comment by iatsdotfatr** [comment]
> Так же не стал создавать классы на checkbox и toggler, т.к. в них я только убираю выделение текста по умолчанию. Создавать класс для этого, по-моему, избыточно.

1. Здесь в принципе использовать js избыточно :), к тому же скрипт чекбоксов почему-то не работает. Используй css.

2. Где возможно, для перебора вместо циклов применяй методы массивов/псевдомассивов
![Screenshot from 2020-07-03 10-20-33](https://user-images.githubusercontent.com/51824674/86431618-1dcb9480-bd17-11ea-99f9-65ddc21ac653.png)

3. Добавь в eslint конфиг Airbnb, также ознакомься с самими правилами [https://github.com/airbnb/javascript](https://github.com/airbnb/javascript), так как конфиг их все не покрывает, и внеси соответствующие правки.

**Comment by GrigorenkoSergey** [comment]
Ну с 1, 2 все ясно. 
По 3-му пункту правило func-style вот прям отталкивает... Брррр... Всегда думал, что hoisting функций - это круто, полезно и вообще... Неужели, прям такие сложности в отладке возникают, что нужно уродовать (по моему скромному мнению) код?

**Comment by GrigorenkoSergey** [comment]
Начинаю ворчать... 
Зачем убирать расширения файлов при импорте??? Я их всегда использую для быстрого поиска и замены...

**Comment by GrigorenkoSergey** [comment]
23.6 Название файла точно должно совпадать с именем его экспорта по умолчанию. Так все-таки как называть файл? Пока оставлю с lower-case-hyphenated.

**Comment by GrigorenkoSergey** [comment]
Отчет по пунктам.
1. Добавил в необходимых местах "user-select: none". 

2. С заменой перебора циклов на методы массивов, мой код заиграл новыми красками!!!  Он последовал новым веяниям моды и добавил капельку летнего настроения в этом сезоне... Вы только посмотрите, как элегантно вписывается в новый стиль оператор расширения )))

3. Внес правки по 3-му пункту, а так же использовал некоторые дополнительные fsd-правила. Возникло несколько вопросов:
а) правило func-style. Все ли у вас его придерживаются?? Hoisting функций, насколько я помню применяется еще в языке Си. И как-то не вызывал никаких вопросов уже сколько лет. 
б) Расширения файлов при импорте. Принципиально ли убирать? Мне оно помогает в поиске/замене. Мы ведь в js-файлах также можем импортировать .scss - файлы с таким же названием. 
в) п.23.6. Название файла должно совпадать с именем его экспорта по умолчанию. Смешивать lower-case-hyphenated и cameslCase (PascalCase) в одном проекте некрасиво на мой взгляд. 
г) В fsd есть правило "no-heavy-constructor". Я перенес методы взаимодействия с DOM в метод класса init(). Что мне делать с теми свойствами, которые я добавляю в свойства класса только после работы с DOM (вызывая в конструкторе this.init())? Стоит ли их инициализировать в конструкторе  null-значением, чтобы показать их наличие, или оставить все как есть (например, как в  dropdown-guests.js).

**Comment by iatsdotfatr** [comment]
а) По идее, у тебя должно вообще было остаться ни function declaration, ни function expression после переписывания кода на классы), в dropdown-origin замени function на метод класса, а date-dropdown перепиши. Не знаю, придерживаются ли все в команде данного правила, я в новом коде встречал function только при использовании генераторов.
б) Не принципиально.
в) Не принципиально.
г) Оставь как есть.

**Comment by GrigorenkoSergey** [comment]
По спецификации [js-datepicker](https://www.npmjs.com/package/js-datepicker#onshow) я должен передать в его метод именно функцию. Разве это будет правильно, если я начну переписывать date-dropdown?

**Comment by GrigorenkoSergey** [comment]
Переименовал обработчики, поменял приведение типов. Пока оставил date-dropdown. Имена обработчиков пока укороченные (без пространства имен).

**Comment by iatsdotfatr** [comment]
> Если да, то как должен именоваться обработчик на самом блоке? handleEventName?

1. Если обработчик на блоке, писать имя блока, Input вместо DropdownInput в большинстве случаев должно быть достаточно.

2. Конструкторы в некоторых классах можно сделать "легковеснее", вплоть до передачи в конструктор одного метода.

**Comment by GrigorenkoSergey** [comment]
Переписал некоторые конструкторы. Немного поменял подход к привязке обработчиков. При старом подходе методы объекта становились видимыми свойствами каждого экземпляра, что не есть хорошо.
Поменял date-dropdown. Так сойдет?
