### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#5]
В одном шаблоне один блок (миксин).
![3 in 1](https://user-images.githubusercontent.com/51824674/85201505-b3cbec00-b321-11ea-8bd4-3b9c259b9c6d.png)

**Comment by GrigorenkoSergey** [comment]
Разбил все, кроме тех что в footer, т.к. там у меня вспомогательные миксины, нигде больше не применимые.

**Comment by iatsdotfatr** [comment]
Создай для них внутри папки footer папку с названием типа blocks или components и положи туда.

**Comment by GrigorenkoSergey** [comment]
Разбивать ли папку components на подпапки, в которых .pug и .scss файлы каждого вспомогательного миксина (вариант 1)? Если да, то как поступить с общими классами в вспопогательных миксинах, которые не встречаются в главном миксине, напр. footer__subscribe? 
Или можно ограничиться только .pug файлами с единым общим footer.scss (вариант 2)?
Пока что я сделал по 1-му варианту и скопировал общий код .footer__subscribe в каждый миксин.

**Comment by iatsdotfatr** [comment]
Миксин это отдельный бэм-блок.

**Comment by GrigorenkoSergey** [comment]
Сделано.

**Comment by iatsdotfatr** [comment]
1. Миксины из папки components футера сейчас не являются бэм-блоками.
2. В данных случаях надо использовать модификатор "ключ-значение", также правило для before используй внутри правила модификатора.

**Comment by GrigorenkoSergey** [comment]
1. Запутался окончательно... Миксины из папки components у меня должны быть элементами, а не отдельными блоками.. 
Немного поменял этот злополучный футер.
2. О каком before идет речь? Их ведь в футере нет.  Имеешь лы ты в виду, что все псевдо классы и псевдоэлементы описывать в таком виде
&__elem {
  &:hover {
    some rules...
  }
}
?

**Comment by iatsdotfatr** [comment]
>     2\. О каком before идет речь?
Картинка где-то потерялась)
![Screenshot from 2020-07-06 21-22-43](https://user-images.githubusercontent.com/51824674/86610297-f7378300-bfce-11ea-8b6d-c7ddd09d4c81.png)

**Comment by GrigorenkoSergey** [comment]
Переделал.

**Comment by iatsdotfatr** [comment]
>     2\. В данных случаях надо использовать модификатор "ключ-значение"
Первую часть комментария пропустил, по всему проекту проверь.

**Comment by GrigorenkoSergey** [comment]
Так это относилось к button-white?!?! Я всю голову сломал и несколько раз перезагрузился, пытаясь понять, какое отношение миксины из футера имеют к модификаторам "ключ-значение" ))) Я чуть не спился из-за этого.. 
Проверил по всему проекту, нашел некорректное применение модификаторов только к button и rate-button.

**Comment by iatsdotfatr** [comment]
1. Привести в соответствие
![bem](https://user-images.githubusercontent.com/51824674/88416249-b24e8180-ce01-11ea-92f8-fbfb28d87b49.png)

2. Два бем-блока в одном миксине
![two classes](https://user-images.githubusercontent.com/51824674/88416292-c6927e80-ce01-11ea-80cd-c9c2e342b498.png)

3. Вот еще кандидат на ключ-значение, и название лучше более семантическое придумать
![key-value](https://user-images.githubusercontent.com/51824674/88416370-e9bd2e00-ce01-11ea-8832-6183ad0d4050.png)

**Comment by GrigorenkoSergey** [comment]
Исправил все что можно.

**Comment by iatsdotfatr** [comment]
>     1. Привести в соответствие
![bem](https://user-images.githubusercontent.com/51824674/88416249-b24e8180-ce01-11ea-92f8-fbfb28d87b49.png)

1. Вот это не исправил, в бэм два типа модификаторов, а это какой-то третий тип ).

2. Здесь, кроме того, что также следует использовать модификатор ключ-значение, сам элемент &__img, без модификаторов, отсутствует, в данном случае в модификаторы следует выносить только правило background-image, остальные правила должны непосредственно в классе &__img, а можно обойтись вообще без модификаторов, если не использовать background-image, а тег img и передавать ему src через аргумент миксина.
![no element](https://user-images.githubusercontent.com/51824674/89726818-c53b9580-da40-11ea-9e7a-7198d8cff2ea.png)

**Comment by GrigorenkoSergey** [comment]
1) Хм... А где это встречается? Что-то я не нашел. Поиск не помог. У меня ведь теперь в итоге получился class="shades__rect  shades__rect_color_dark_50". Разве shades__rect_color_dark_50 - неправильное имя модификатора? (правда, там должен быть background-color, но не суть..) Немного не пойму.. В примере модификаторов есть такой: search-form__button_size_s.
Мне сделать так: shades__rect shades__rect_bg-color_dark-50?

**Comment by iatsdotfatr** [comment]
1. Встречается здесь, поэтому правильно сделал).
![Screenshot from 2020-08-15 15-40-26](https://user-images.githubusercontent.com/51824674/90309894-421db200-df0e-11ea-9b07-ec1920faf974.png)

2. 
  а) В данном случае точно не является.
  б) Все нормально, поскольку здесь не требуется какая-то конкретная анимация изменения иконки, а если вдруг 
      потребуется, то тогда станет понятно, в зависимости от вида анимации, какой подход лучше.

**Comment by iatsdotfatr** [comment]
Несмотря на то, что адаптив здесь не требуется, фиксированную ширину лучше не использовать
![max-width](https://user-images.githubusercontent.com/51824674/91166265-ec0df300-e6f3-11ea-8c0b-58370349dbbc.png)

**Comment by GrigorenkoSergey** [comment]
Хм.. ну max-width подойдет? Или сделать внешнему блоку margin или padding? Сделал через padding.

**Comment by iatsdotfatr** [comment]
max-width подойдет
