### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#6]
![Screenshot from 2020-07-03 10-26-26](https://user-images.githubusercontent.com/51824674/86431853-afd39d00-bd17-11ea-970c-027ed11440c4.png)
![negmargin](https://user-images.githubusercontent.com/51824674/86431855-b19d6080-bd17-11ea-8285-f05228d3c2fe.png)

**Comment by GrigorenkoSergey** [comment]
Исправил.

**Comment by iatsdotfatr** [comment]
Height использовать только там, где это необходимо, правило есть в стандартах, в этих случаях это не является необходимостью, проверить по всему проекту
![unnecessary height](https://user-images.githubusercontent.com/51824674/87054330-cd779980-c224-11ea-9ee7-b439a4e30524.png)
![use paddings](https://user-images.githubusercontent.com/51824674/87054339-cea8c680-c224-11ea-8416-1359db7e05b5.png)

**Comment by GrigorenkoSergey** [comment]
Убрал.

**Comment by iatsdotfatr** [comment]
![Screenshot from 2020-08-09 13-25-27](https://user-images.githubusercontent.com/51824674/89727118-d639d600-da43-11ea-8333-2a238f1928d6.png)
![Screenshot from 2020-08-09 13-18-24](https://user-images.githubusercontent.com/51824674/89727122-d89c3000-da43-11ea-92e0-b532c8e07ff6.png)
По всему проекту

**Comment by GrigorenkoSergey** [comment]
Убрал везде, где можно. Однако, в некоторых местах все же оставил. Например, в .template__logo, там этот значок не нужен в потоке.

**Comment by iatsdotfatr** [comment]
1. Используй padding, а не line-height
2. Лучше используй width 100%, а уже на месте помещай в контейнер нужной ширины, иначе слишком узкий модификатор получается.
![Screenshot from 2020-08-15 16-33-15](https://user-images.githubusercontent.com/51824674/90310697-c6276800-df15-11ea-9593-104f35e7417b.png)

**Comment by GrigorenkoSergey** [comment]
Исправил.

**Comment by iatsdotfatr** [comment]
> Очень странное и неоднозначное (на мой опытный стажерский взгляд) правило
Все состояния сущности находятся в одном месте.

Одинаковые правила в идущих подряд медиазапросах:
![same rules](https://user-images.githubusercontent.com/51824674/91167562-f7fab480-e6f5-11ea-8c57-0d445342181a.png)
![same rules2](https://user-images.githubusercontent.com/51824674/91167573-fc26d200-e6f5-11ea-9170-acfb8efe3912.png)

**Comment by GrigorenkoSergey** [comment]
Да, че то я схалтурил... Исправил.
