### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/FSDEducation-second-task#7]
1. Полагаю, эта часть нигде не используется, лучше ее убрать отовсюду, где она есть.
![unnecessary](https://user-images.githubusercontent.com/51824674/87054844-6ad2cd80-c225-11ea-819d-f48cc09c74a3.png)

2. Убрать хардкод, оставить только переменные, по всему проекту. Ну и в данном случае привести в соответсвие с БЭМ.
![remove hardcode](https://user-images.githubusercontent.com/51824674/87055117-bd13ee80-c225-11ea-9ac8-bc89c20a5048.png)

3. Лучше не писать ничего над объявлением миксина, кроме импортов, все нужные данные передавай объектом в параметры, объект деструктурируй или непосредственно в параметрах, или в теле миксина, если у объекта много полей и строка получается слишком длинной, вместе с деструктуризацией используй и default parameters, там, где надо.
![Screenshot from 2020-07-09 20-51-03](https://user-images.githubusercontent.com/51824674/87055885-b46fe800-c226-11ea-9509-2587d70fb5eb.png)

**Comment by GrigorenkoSergey** [comment]
1. Подход с extraClasses был задуман как возможность добавления дополнительных стилей к каждому составляющему блок элементу. У вас другой подход, в котором вы кастомизируете компонент, вроде
```
   promo-page
     +header({ theme: 'transparent', font: 'light' })
```
Я правильно понял, что вы не закладываете возможность модификации блока извне, а в случае необходимости, просто переписываете блок, добавляя нужные для модификации опции? Т.е. максимально лениво? )))

**Comment by iatsdotfatr** [comment]
Да, примеси не используются.

**Comment by GrigorenkoSergey** [comment]
1.Исправил, хотя модификаторы у меня передаются как строка с классом элемента, а не как объект. 
2. Этого не понял. У меня ведь шаблон, разметка. Из всех подчеркнутых строк там ведь только меняется количество голосов. Я бы там мог написать что угодно, все-равно подставится нужное значение.

**Comment by iatsdotfatr** [comment]
>     3. Разве это не затруднит в дальнейшем чтение кода? Я специально вынес дефолтный объект из миксина, чтобы потом при дальнейшем использовании миксина не запутаться.

Так с деструктуризацией как раз видно что, откуда и куда приходит. А про default parameters  я и написал, что по желанию.

**Comment by GrigorenkoSergey** [comment]
Уф... Сделал ))) Переписал все миксины в соответствии с требованием пункта 3.

**Comment by GrigorenkoSergey** [comment]
PS. Я сейчас в отпуске, времени гораздо больше, поэтому буду все исправлять оперативнее )) Можешь еще раз пальцем ткнуть на issues, которые не исправлены и закрыть исправленные? А то я спорил, аргументировал... И в итоге не понятно, то ли со мной согласились, то ли просто покрутили пальцем у виска и не стали спорить с убогим )

**Comment by iatsdotfatr** [comment]
Задание обучающее, поэтому хардкод из диаграммы надо убрать, чтобы компонент был максимально кастомирзируемым, вдруг надо будет (нет) поменять язык. Также миксин не соотвествует БЭМ, элемент это "что", а не "какой". И приведи деструктуризацию к одному виду, у тебя то var, то let, лучше используй const.

**Comment by GrigorenkoSergey** [comment]
1. Исправил.
2. Разбил все страницы на отдельные миксины. Однако, оставить только pug- файлы в папке pages не смог. Пришлось оставить еще и js-файлы. Пока не представляю как подключить scss файлы без них. Экспериментировал с require.context, но все неудачно.

**Comment by GrigorenkoSergey** [comment]
Исправил. Единиственное, что не смог оставить только pug-файлы в pages. Не знаю, как обойтись без js-файлов, подключающих стили.  Сразу вопрос. В каждом блоке стили лучше импортировать через js-файл или все-таки в scss-айлах?

**Comment by iatsdotfatr** [comment]
> В каждом блоке стили лучше импортировать в js или scss-файлах?

Можно настроить автоматический импорт, например, см. webpack dependency management, или через какой-нибудь модуль.

**Comment by GrigorenkoSergey** [comment]
Вот здесь не понял.. Читать ли твой ответ в стиле: "Исправить обязательно!!! Вот тебе спецификация, вот тебе компьютер,  приду проверю.. " или "Теоретически-то можно... но ладно, и так сойдет ))."

**Comment by GrigorenkoSergey** [comment]
Ну, в общем, я разобрался.... Я так понял, что мы просто подгружаем ВСЕ js-файлы в индекс, игнорируем возможности разбиения по чанкам в HtmlWebpackPlugin (должен тупо весь код загрузиться, и становится неважно, где ты там подключаешь тот или иной файл js) потом на выходе получаем неимоверно раздутые файлы scss и js. Героическое использование оптимизации нам позволит чуть-чуть уменьшить код.. Поэтому при использовании различных минификаторов и оптимизаторов у меня размер файлов на выходе не уменьшился ВООБЩЕ. Поэтому в итоге я их и удалил...
Оно так-то конечно проще в разработке, можно выиграть пару минут в день, но понравится ли это пользователю?
Хотя, возможно, я просто не так все понял.

**Comment by GrigorenkoSergey** [comment]
Отвечая на собственный вопрос, лучше подключать стилевые файлы именно чере js, т.к. тогда не будет дублирования css-кода )) Буду переписывать...

**Comment by iatsdotfatr** [comment]
Подключай то что нужно, и не подключай то, что не нужно). @thunderleg

**Comment by GrigorenkoSergey** [comment]
`Подключай то что нужно, и не подключай то, что не нужно`
Переписал архитектуру... Теперь мне не нужна оптимизация кода....

Как тебе такое, **iatsdotfatr**?
